title:              Basit Anwer
tagline:            Engineer, Programmer, Geek and Gamer
description:        Discussion everything tech related.
url:                http://basitanwer.github.io
google_analytics:   [ Your Google Analytics tracking ID]

author:
  name:             Basit Anwer
  url:              https://twitter.com/basit_anwer
  email:            anwer.basit@gmail.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post

theme: minima
